title: Everyday Learning Analytics @ Aleksandra Pilot 1 (04.03.2017)
author: Luis P. Prieto
email: lprisan@tlu.ee
description: A prototype of what Everyday Learning Analytics might look like
baseurl: /EverydayLA-Prototype4Alexa

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
