title: Everyday Learning Analytics @ ...Event/Course... (...Date...)
author: Luis P. Prieto
email: lprisan@tlu.ee
description: A prototype of what Everyday Learning Analytics might look like
baseurl: /EverydayLA-Prototype4Base

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
